"""Add scheduled_time to ScheduledTask

Revision ID: 239ee1351142
Revises: 053bb74d5e4e
Create Date: 2025-07-08 12:29:33.945020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239ee1351142'
down_revision: Union[str, Sequence[str], None] = '053bb74d5e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('downtime_events_machine_id_fkey'), 'downtime_events', type_='foreignkey')
    op.create_foreign_key(None, 'downtime_events', 'machines', ['machine_id'], ['id'], ondelete='CASCADE')
    op.add_column('scheduled_tasks', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_tasks', 'scheduled_time')
    op.drop_constraint(None, 'downtime_events', type_='foreignkey')
    op.create_foreign_key(op.f('downtime_events_machine_id_fkey'), 'downtime_events', 'machines', ['machine_id'], ['id'])
    # ### end Alembic commands ###
