"""Refine datetime handling across scheduler

Revision ID: 3437a899ea4c
Revises: f22fe3519964
Create Date: 2025-06-26 21:24:06.763023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3437a899ea4c'
down_revision: Union[str, Sequence[str], None] = 'f22fe3519964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
