"""Add Operator Machine-Queue and user-machine association

Revision ID: 4936ea1a9205
Revises: 60df6edb59d9
Create Date: 2025-07-17 23:29:21.349354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4936ea1a9205'
down_revision: Union[str, Sequence[str], None] = '60df6edb59d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_machine_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'machine_id')
    )
    op.add_column('downtime_events', sa.Column('comments', sa.Text(), nullable=True))
    op.add_column('scheduled_tasks', sa.Column('job_id_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'scheduled_tasks', ['job_id_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_tasks', type_='unique')
    op.drop_column('scheduled_tasks', 'job_id_code')
    op.drop_column('downtime_events', 'comments')
    op.drop_table('user_machine_association')
    # ### end Alembic commands ###
