"""Add block_reason column to scheduled_tasks

Revision ID: 60df6edb59d9
Revises: 239ee1351142
Create Date: 2025-07-15 13:36:58.215009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60df6edb59d9'
down_revision: Union[str, Sequence[str], None] = '239ee1351142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_tasks', sa.Column('block_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_tasks', 'block_reason')
    # ### end Alembic commands ###
