"""Fix native_enum to false for models.py

Revision ID: a38f804d4e58
Revises: 40ff95104fbc
Create Date: 2025-06-27 00:41:59.267565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a38f804d4e58'
down_revision: Union[str, Sequence[str], None] = '40ff95104fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_logs', 'status',
               existing_type=postgresql.ENUM('pending', 'scheduled', 'in_progress', 'completed', name='joblog_status_enum'),
               type_=sa.Enum('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='joblog_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::joblog_status_enum"))
    op.alter_column('production_orders', 'current_status',
               existing_type=postgresql.ENUM('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='order_status_enum'),
               type_=sa.Enum('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='order_status_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'current_status',
               existing_type=sa.Enum('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='order_status_enum', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='order_status_enum'),
               existing_nullable=False)
    op.alter_column('job_logs', 'status',
               existing_type=sa.Enum('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='joblog_status_enum', native_enum=False),
               type_=postgresql.ENUM('pending', 'scheduled', 'in_progress', 'completed', name='joblog_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::joblog_status_enum"))
    # ### end Alembic commands ###
